ads/urls.py
from django.urls import path
from .views import AdsList, AdsDetail, AdsCreateView, AdsUpdateView, AdsDeleteView, AdsOwnList

app_name = "ads"
urlpatterns = [
    path("", AdsList, name="ads-list"),
    path("ajouter", AdsCreateView.as_view(), name="ads-new"),
    path("mes-annonces", AdsOwnList, name="ads-own-list"),
    path("<int:pk>", AdsDetail, name="ads-detail"),
    path("<int:pk>/editer", AdsUpdateView.as_view(), name="ads-edit"),
    path("<int:pk>/supprimer", AdsDeleteView.as_view(), name="ads-delete"),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import register, view_login, view_logout

from .views import index

urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('unicorn/', include("django_unicorn.urls")),
    path('fiches-d-elevage/', include('card.urls', namespace="card")),
    path('petites-annonces/', include('ads.urls', namespace="ads")),
    path("terrariopedia/", include("django.contrib.flatpages.urls")),
    path("communaute/", include('member.urls', namespace="member")),
    path("documentations/", include('documentation.urls', namespace="documentation")),
    path("register", register, name="register"),
    path("login", view_login, name="login"),
    path("logout", view_logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from sorl.thumbnail import ImageField

def ads_directory_path(instance, filename):
    return 'medias/uploads/images/ads/{0}/{1}'.format(instance.owner.username, filename)

class Ads(models.Model):
    TYPE_OF_ADS = (
        ('R', 'Recherche'),
        ('V', 'Vends')
    )
    CATEGORIES = (
        ('A', 'Amphibiens'),
        ('R', 'Arthropodes'),
        ('L', 'Lézards'),
        ('S', 'Serpents'),
        ('M', 'Matériels et terrarium')
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=1, verbose_name="Catégorie", choices=CATEGORIES)
    type_of_ads = models.CharField(max_length=1, verbose_name='Type d\'annonce', choices=TYPE_OF_ADS)
    image = ImageField(upload_to=ads_directory_path, blank=True)
    description = models.TextField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Petite annonce de {self.owner} publié le {self.created_at}"

    def get_absolute_url(self):
        return reverse("ads-detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Petite annonce'
        verbose_name_plural = 'Petites annonces'

ads/forms.py
from django.forms import ModelForm
from django import forms
from .models import Ads
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django_countries.fields import CountryField

class AdsForm(ModelForm):
    class Meta:
        model = Ads
        fields = ('category', 'type_of_ads', 'description', 'image')
        exclude = ('created_at',)

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

ads/views.py
from django.shortcuts import render
from .models import Ads
from .forms import AdsForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy

def AdsList(request):
    return render(request, "ads/ads-list.html")

def AdsOwnList(request):
    return render(request, "ads/ads-own-list.html", {'owner': request.user.pk})

def AdsDetail(request, pk):
    return render(request, "ads/ads-detail.html", {"pk": pk})

@method_decorator(login_required, name='dispatch')
class AdsCreateView(CreateView):
    model = Ads
    form_class = AdsForm
    template_name = 'ads/ads-form.html'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('ads:ads-detail', kwargs={'pk': self.object.pk})

@method_decorator(login_required, name='dispatch')
class AdsUpdateView(UpdateView):
    model = Ads
    form_class = AdsForm
    template_name = 'ads/ads-form.html'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('ads:ads-detail', kwargs={'pk': self.object.pk})

@method_decorator(login_required, name='dispatch')
class AdsDeleteView(DeleteView):
    model = Ads
    success_url = reverse_lazy("ads:ads-list")

ads/templates/unicorn/ads-detail.html
{% load thumbnail %}{% load static %}
<div class="row">
    <div class="col-md-4">
        {% thumbnail ads.image "400x300" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top"
                 alt="TerrarioPedia - Petites annonces - {{ ads.get_category_display }}"/>
        <hr />
        {% endthumbnail %}

        {% if ads.owner == request.user %}
        <a href="{% url 'ads:ads-edit' ads.pk %}" class="btn btn-warning btn-block" title="TerrarioPedia - Petites annonces - {{ ads.get_category_display }} - Editer">Editer</a>
        <a href="{% url 'ads:ads-delete' ads.pk %}" class="btn btn-danger btn-block" title="TerrarioPedia - Petites annonces - {{ ads.get_category_display }} - Editer">Supprimer</a><br />
        {% endif %}
        <strong>Publié par</strong><br /> {{ ads.owner.get_full_name }} le {{ ads.created_at|date:"d F Y" }}
    </div>
    <div class="col-md-6">
        <h2>{{ ads.get_type_of_ads_display }} - {{ ads.get_category_display }}</h2>
            {{ ads.description|linebreaksbr }}
        </div>
    </div>
</div>

ads/templates/unicorn/ads-form.html
{% load crispy_forms_tags %}
<div class="row">
    {% if form.errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
        <div id="form_errors">
            {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% crispy form %}
</div>

ads/templates/unicorn/ads-list.html
{% load sorl_thumbnail %}
<div class="row">
    {% for ad in ads %}
        <div class="col-sm-6 col-xl-3">
            <div class="card overflow-hidden rounded-2">
                <div class="position-relative">
                    <a href="{% url 'ads:ads-detail' ad.pk %}"
                       title="TerrarioPedia - Petites annonces - {{ ad.get_category_display }}">
                       {% thumbnail ad.image "335x235" crop="center" as im %}
                         <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top"
                         alt="TerrarioPedia - Petites annonces - {{ ad.get_category_display }}"/>
                        {% endthumbnail %}</a>
                </div>
                <div class="card-body pt-3 p-4">
                    <h6 class="fw-semibold fs-4">{{ ad.get_category_display }}</h6>
                    <a href="{% url 'ads:ads-detail' ad.pk %}" class="text-decoration-none text-dark"
                       title="TerrarioPedia - Petites annonces - {{ ad.get_category_display }}">{{ ad.description|truncatewords:"20" }}</a>
                </div>
                <div class="card-footer">
                    Publié le: {{ ad.created_at }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

ads/templates/unicorn/ads-own-list.html
{% load sorl_thumbnail %}
<div class="row">
    {% for ad in ads %}
        <div class="col-sm-6 col-xl-3">
            <div class="card overflow-hidden rounded-2">
                <div class="position-relative">
                    <a href="{% url 'ads:ads-detail' ad.pk %}"
                       title="TerrarioPedia - Mes annonces - {{ ad.get_category_display }}">
                       {% thumbnail ad.image "335x235" crop="center" as im %}
                         <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top"
                         alt="TerrarioPedia - Mes annonces - {{ ad.get_category_display }}"/>
                        {% endthumbnail %}</a>
                </div>
                <div class="card-body pt-3 p-4">
                    <h6 class="fw-semibold fs-4">{{ ad.get_category_display }}</h6>
                    {{ ad.description|truncatewords:"20" }}
                </div>
                <div class="card-footer">
                    Publié le: {{ ad.created_at }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>