ads/urls.py
from django.urls import path
from .views import AdsList, AdsDetail, AdsCreateView, AdsUpdateView, AdsDeleteView, AdsOwnList

app_name = "ads"
urlpatterns = [
    path("", AdsList, name="ads-list"),
    path("ajouter", AdsCreateView.as_view(), name="ads-new"),
    path("mes-annonces", AdsOwnList, name="ads-own-list"),
    path("<int:pk>", AdsDetail, name="ads-detail"),
    path("<int:pk>/editer", AdsUpdateView.as_view(), name="ads-edit"),
    path("<int:pk>/supprimer", AdsDeleteView.as_view(), name="ads-delete"),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import register, view_login, view_logout

from .views import index

urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('unicorn/', include("django_unicorn.urls")),
    path('fiches-d-elevage/', include('card.urls', namespace="card")),
    path('petites-annonces/', include('ads.urls', namespace="ads")),
    path("terrariopedia/", include("django.contrib.flatpages.urls")),
    path("communaute/", include('member.urls', namespace="member")),
    path("documentations/", include('documentation.urls', namespace="documentation")),
    path("register", register, name="register"),
    path("login", view_login, name="login"),
    path("logout", view_logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

card/urls.py
from django.urls import path

from .views import AmphibianList, AmphibianDetail, AmphibianCreateView, AmphibianUpdateView, \
    ArthropodList, ArthropodDetail, ArthropodCreateView, ArthropodUpdateView, \
    LizardList, LizardDetail, LizardCreateView, LizardUpdateView, \
    SnakeList, SnakeDetail, SnakeCreateView, SnakeUpdateView, \
    TurtleList, TurtleDetail, TurtleCreateView, TurtleUpdateView

app_name = "card"
urlpatterns = [
    path("amphibiens/", AmphibianList, name="amphibian-list"),
    path("amphibiens/ajouter", AmphibianCreateView.as_view(), name="amphibian-new"),
    path("amphibiens/<slug:slug>/editer", AmphibianUpdateView.as_view(), name="amphibian-edit"),
    path("amphibiens/<slug:slug>", AmphibianDetail, name="amphibian-detail"),

    path("arthropodes/", ArthropodList, name="arthropod-list"),
    path("arthropodes/ajouter", ArthropodCreateView.as_view(), name="arthropod-new"),
    path("arthropodes/<slug:slug>/editer", ArthropodUpdateView.as_view(), name="arthropod-edit"),
    path("arthropodes/<slug:slug>", ArthropodDetail, name="arthropod-detail"),

    path("lezards/", LizardList, name="lizard-list"),
    path("lezards/ajouter", LizardCreateView.as_view(), name="lizard-new"),
    path("lezards/<slug:slug>/editer", LizardUpdateView.as_view(), name="lizard-edit"),
    path("lezards/<slug:slug>", LizardDetail, name="lizard-detail"),

    path("serpents/", SnakeList, name="snake-list"),
    path("serpents/ajouter", SnakeCreateView.as_view(), name="snake-new"),
    path("serpents/<slug:slug>/editer", SnakeUpdateView.as_view(), name="snake-edit"),
    path("serpents/<slug:slug>", SnakeDetail, name="snake-detail"),

    path("tortues/", TurtleList, name="turtle-list"),
    path("tortues/ajouter", TurtleCreateView.as_view(), name="turtle-new"),
    path("tortues/<slug:slug>/editer", TurtleUpdateView.as_view(), name="turtle-edit"),
    path("tortues/<slug:slug>", TurtleDetail, name="turtle-detail"),
]

card/forms.py
from django import forms
from django.forms import ModelForm
from .models import Card, Amphibian, Lizard
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Amphibian, Arthropod, Lizard, Snake, Turtle

class SnakeForm(ModelForm):
    class Meta:
        model = Snake
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

class ArthropodForm(ModelForm):
    class Meta:
        model = Arthropod
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

class AmphibianForm(ModelForm):
    class Meta:
        model = Amphibian
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

class LizardForm(ModelForm):
    class Meta:
        model = Lizard
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

class TurtleForm(ModelForm):
    class Meta:
        model = Turtle
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

card/views.py
from django.shortcuts import render
from .models import Amphibian, Arthropod, Lizard, Snake, Turtle
from .forms import AmphibianForm, ArthropodForm, LizardForm, SnakeForm, TurtleForm
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse

def AmphibianList(request):
    return render(request, "card/amphibian-list.html")

def AmphibianDetail(request, slug):
    return render(request, "card/amphibian-detail.html", {"slug": slug})

def ArthropodList(request):
    return render(request, "card/arthropod-list.html")

def ArthropodDetail(request, slug):
    return render(request, "card/arthropod-detail.html", {"slug": slug})

def LizardList(request):
    return render(request, "card/lizard-list.html")

def LizardDetail(request, slug):
    return render(request, "card/lizard-detail.html", {"slug": slug})

def SnakeList(request):
    return render(request, "card/snake-list.html")

def SnakeDetail(request, slug):
    return render(request, "card/snake-detail.html", {"slug": slug})

def TurtleList(request):
    return render(request, "card/turtle-list.html")

def TurtleDetail(request, slug):
    return render(request, "card/turtle-detail.html", {"slug": slug})

# Formulaires
@method_decorator(login_required, name='dispatch')
class SnakeCreateView(CreateView):
    model = Snake
    form_class = SnakeForm
    template_name = 'card/snake-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:snake-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class SnakeUpdateView(UpdateView):
    model = Snake
    form_class = SnakeForm
    template_name = 'card/snake-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:snake-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class AmphibianCreateView(CreateView):
    model = Amphibian
    form_class = AmphibianForm
    template_name = 'card/amphibian-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:amphibian-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class AmphibianUpdateView(UpdateView):
    model = Amphibian
    form_class = AmphibianForm
    template_name = 'card/amphibian-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:amphibian-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class LizardCreateView(CreateView):
    model = Lizard
    form_class = LizardForm
    template_name = 'card/lizard-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:lizard-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class LizardUpdateView(UpdateView):
    model = Lizard
    form_class = LizardForm
    template_name = 'card/lizard-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:lizard-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class ArthropodCreateView(CreateView):
    model = Arthropod
    form_class = ArthropodForm
    template_name = 'card/arthropod-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:arthropod-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class ArthropodUpdateView(UpdateView):
    model = Arthropod
    form_class = ArthropodForm
    template_name = 'card/arthropod-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:arthropod-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class TurtleCreateView(CreateView):
    model = Turtle
    form_class = TurtleForm
    template_name = 'card/turtle-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:turtle-detail', kwargs={'slug': self.object.slug})

@method_decorator(login_required, name='dispatch')
class TurtleUpdateView(UpdateView):
    model = Turtle
    form_class = TurtleForm
    template_name = 'card/turtle-form.html'

    def form_valid(self, form):
        form.instance.last_owner = self.request.user
        if form.is_valid():
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('card:turtle-detail', kwargs={'slug': self.object.slug})

card/templates/card/amphibian-detail.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Amphibiens{% endblock %}

{% block title %}Amphibiens{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Fiches d'élevage d'amphibiens</h5>
                     {% unicorn 'amphibian-detail' slug=slug %}
                 </div>
             </div>
         </div>
</div>
{% endblock %}

card/templates/card/amphibian-form.html
{% extends 'base.html' %}
{% load unicorn %}
{% load crispy_forms_tags %}
{% block page_title %}Formulaire d'amphibien{% endblock %}
{% block title %}Formulaire d'amphibien{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Formulaire d'élevage d'amphibiens</h5>
                       {% unicorn "amphibian-form" %}
                 </div>
             </div>
         </div>
</div>

{% endblock %}

card/templates/card/amphibian-list.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Amphibiens{% endblock %}

{% block title %}Amphibiens{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Fiches d'élevage d'amphibiens</h5>
                     <a href="{% url 'card:amphibian-new' %}" class="btn btn-outline-primary mb-3" title="TerrarioPedia - Ajouter une fiche d'élevage d'amphibien">Nouvelle fiche</a>
                      {% unicorn 'amphibian-list' quantity="0" %}
                 </div>
             </div>
         </div>
</div>
{% endblock %}

card/templates/card/arthropod-form.html
{% extends 'base.html' %}
{% load unicorn %}
{% load crispy_forms_tags %}
{% block page_title %}Formulaire d'arthropode{% endblock %}
{% block title %}Formulaire d'arthropod{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Formulaire d'élevage d'arthropode</h5>
                       {% unicorn "arthropod-form" %}
                 </div>
             </div>
         </div>
</div>

{% endblock %}

card/templates/card/arthropod-list.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Arthropodes{% endblock %}

{% block title %}Arthropodes{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Fiches d'élevage d'arthropodes</h5>
                     <a href="{% url 'card:arthropod-new' %}" class="btn btn-outline-primary mb-3" title="TerrarioPedia - Ajouter une fiche d'élevage d'arthropode">Nouvelle fiche</a>
                     {% unicorn 'arthropod-list' quantity="0" %}
                 </div>
             </div>
         </div>
</div>
{% endblock %}

card/templates/card/lizard-detail.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Amphibiens{% endblock %}

{% block title %}Amphibiens{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Fiches d'élevage de lézards</h5>
                     {% unicorn 'lizard-detail' slug=slug %}
                 </div>
             </div>
         </div>
</div>
{% endblock %}

card/templates/card/lizard-form.html
{% extends 'base.html' %}
{% load unicorn %}
{% load crispy_forms_tags %}
{% block page_title %}Formulaire de lézard{% endblock %}
{% block title %}Formulaire de lézard{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Formulaire d'élevage de lézard</h5>
                       {% unicorn "lizard-form" %}
                 </div>
             </div>
         </div>
</div>

{% endblock %}

card/templates/card/lizard-list.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Lézards{% endblock %}

{% block title %}Lézards{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Fiches d'élevage de lézards</h5>
                     <a href="{% url 'card:lizard-new' %}" class="btn btn-outline-primary mb-3" title="TerrarioPedia - Ajouter une fiche d'élevage de lézard">Nouvelle fiche</a>
                    <div class="row">
                      {% unicorn 'lizard-list' quantity="0" %}
                    </div>
                 </div>
             </div>
         </div>
</div>
{% endblock %}

card/templates/card/snake-detail.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Serpents{% endblock %}

{% block title %}Serpents{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Fiches d'élevage de serpents</h5>
                     {% unicorn 'snake-detail' slug=slug %}
                 </div>
             </div>
         </div>
</div>
{% endblock %}

card/templates/card/snake-form.html
{% extends 'base.html' %}
{% load unicorn %}
{% load crispy_forms_tags %}
{% block page_title %}Formulaire de serpent{% endblock %}
{% block title %}Formulaire de serpent{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Formulaire d'élevage de serpent</h5>
                       {% unicorn "snake-form" %}
                 </div>
             </div>
         </div>
</div>

{% endblock %}

card/templates/card/snake-list.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Serpents{% endblock %}

{% block title %}Serpents{% endblock %}

{% block content %}
<div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                      <h5 class="card-title fw-semibold mb-4">Fiches d'élevage de serpents</h5>
                     <a href="{% url 'card:snake-new' %}" class="btn btn-outline-primary mb-3" title="TerrarioPedia - Ajouter une fiche d'élevage de serpent">Nouvelle fiche</a>
                      {% unicorn 'snake-list' quantity="0" %}
                 </div>
             </div>
         </div>
</div>
{% endblock %}

card/templates/card/turtle-detail.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Tortues{% endblock %}

{% block title %}Tortues{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Fiches d'élevage de tortues</h5>
                     {% unicorn 'turtle-detail' slug=slug %}
                 </div>
             </div>
         </div>
</div>
{% endblock %}

card/templates/card/turtle-form.html
{% extends 'base.html' %}
{% load unicorn %}
{% load crispy_forms_tags %}
{% block page_title %}Formulaire de tortue{% endblock %}
{% block title %}Formulaire de tortue{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Formulaire d'élevage de tortue</h5>
                       {% unicorn "turtle-form" %}
                 </div>
             </div>
         </div>
</div>

{% endblock %}

card/templates/card/turtle-list.html
{% extends 'base.html' %}{% load unicorn %}
{% block page_title %}Tortues{% endblock %}

{% block title %}Tortues{% endblock %}

{% block content %}
  <div class="container-fluid">
         <div class="container-fluid">
             <div class="card">
                 <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Fiches d'élevage de tortue</h5>
                     <a href="{% url 'card:turtle-new' %}" class="btn btn-outline-primary mb-3" title="TerrarioPedia - Ajouter une fiche d'élevage de lézard">Nouvelle fiche</a>
                    <div class="row">
                      {% unicorn 'turtle-list' quantity="0" %}
                    </div>
                 </div>
             </div>
         </div>
</div>
{% endblock %}