ads/urls.py
from django.urls import path
from .views import AdsList, AdsDetail, AdsCreateView, AdsUpdateView, AdsDeleteView, AdsOwnList

app_name = "ads"
urlpatterns = [
    path("", AdsList, name="ads-list"),
    path("ajouter", AdsCreateView.as_view(), name="ads-new"),
    path("mes-annonces", AdsOwnList, name="ads-own-list"),
    path("<int:pk>", AdsDetail, name="ads-detail"),
    path("<int:pk>/editer", AdsUpdateView.as_view(), name="ads-edit"),
    path("<int:pk>/supprimer", AdsDeleteView.as_view(), name="ads-delete"),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import register, view_login, view_logout

from .views import index

urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('unicorn/', include("django_unicorn.urls")),
    path('fiches-d-elevage/', include('card.urls', namespace="card")),
    path('petites-annonces/', include('ads.urls', namespace="ads")),
    path("terrariopedia/", include("django.contrib.flatpages.urls")),
    path("communaute/", include('member.urls', namespace="member")),
    path("documentations/", include('documentation.urls', namespace="documentation")),
    path("register", register, name="register"),
    path("login", view_login, name="login"),
    path("logout", view_logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

card/urls.py
from django.urls import path

from .views import AmphibianList, AmphibianDetail, AmphibianCreateView, AmphibianUpdateView, \
    ArthropodList, ArthropodDetail, ArthropodCreateView, ArthropodUpdateView, \
    LizardList, LizardDetail, LizardCreateView, LizardUpdateView, \
    SnakeList, SnakeDetail, SnakeCreateView, SnakeUpdateView, \
    TurtleList, TurtleDetail, TurtleCreateView, TurtleUpdateView

app_name = "card"
urlpatterns = [
    path("amphibiens/", AmphibianList, name="amphibian-list"),
    path("amphibiens/ajouter", AmphibianCreateView.as_view(), name="amphibian-new"),
    path("amphibiens/<slug:slug>/editer", AmphibianUpdateView.as_view(), name="amphibian-edit"),
    path("amphibiens/<slug:slug>", AmphibianDetail, name="amphibian-detail"),

    path("arthropodes/", ArthropodList, name="arthropod-list"),
    path("arthropodes/ajouter", ArthropodCreateView.as_view(), name="arthropod-new"),
    path("arthropodes/<slug:slug>/editer", ArthropodUpdateView.as_view(), name="arthropod-edit"),
    path("arthropodes/<slug:slug>", ArthropodDetail, name="arthropod-detail"),

    path("lezards/", LizardList, name="lizard-list"),
    path("lezards/ajouter", LizardCreateView.as_view(), name="lizard-new"),
    path("lezards/<slug:slug>/editer", LizardUpdateView.as_view(), name="lizard-edit"),
    path("lezards/<slug:slug>", LizardDetail, name="lizard-detail"),

    path("serpents/", SnakeList, name="snake-list"),
    path("serpents/ajouter", SnakeCreateView.as_view(), name="snake-new"),
    path("serpents/<slug:slug>/editer", SnakeUpdateView.as_view(), name="snake-edit"),
    path("serpents/<slug:slug>", SnakeDetail, name="snake-detail"),

    path("tortues/", TurtleList, name="turtle-list"),
    path("tortues/ajouter", TurtleCreateView.as_view(), name="turtle-new"),
    path("tortues/<slug:slug>/editer", TurtleUpdateView.as_view(), name="turtle-edit"),
    path("tortues/<slug:slug>", TurtleDetail, name="turtle-detail"),
]

card/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse

from sorl.thumbnail import ImageField

class Prey(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Proie"
        verbose_name_plural = "Proies"

class Biotop(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Biotope"
        verbose_name_plural = "Biotopes"

class LifeCommunity(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Vie en communauté"
        verbose_name_plural = "Vies en communauté"

class ReproductionPeriod(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Période de reproduction"
        verbose_name_plural = "Périodes de reproduction"

class Card(models.Model):
    BITE_DANGEROSITY_CHOICES = (
        ('I', 'Inofensif'),
        ('P', 'Pouvant entraîner des dommages'),
        ('D', 'Dangereux'),
        ('E', 'Extrêmement dangereux')
    )
    DIFFICULTY_LEVEL_CHOICE = (
        ('N', 'Pour éleveur débutant (premières espèces)'),
        ('B', 'Pour éleveur ayant déjà une base'),
        ('E', 'Pour éleveur expérimenté'),
        ('X', 'Pour éleveur très expérimenté')
    )
    MORES_CHOICES = (
        ('F', 'Fouisseur'),
        ('T', 'Terrestre'),
        ('A', 'Arboricole')
    )
    ACTIVITY_PERIOD_CHOICES = (
        ('N', 'Nocturne'),
        ('D', 'Diurne'),
        ('A', 'Aube/Crépusculaire')
    )
    BEHAVIOR_CHOICES = (
        ('P', 'Placide'),
        ('F', 'Fuyard'),
        ('D', 'Démonstratif'),
        ('I', 'Irascible')
    )
    REPRODUCTIONS = (
        ('O', 'Ovipare'),
        ('V', 'Vivipare'),
        ('I', 'Ovovivipare')
    )
    genus = models.CharField(max_length=64, verbose_name="Genre", help_text="Exemple: Thamnophis")
    species = models.CharField(max_length=128, verbose_name="Espèce (sous-espèce)", help_text="Exemple : sirtalis similis")
    is_cites = models.BooleanField()
    bern_convention_annex = models.PositiveSmallIntegerField(blank=True, null=True, default=0, help_text="Laissez vide si l'espèce ne figure pas dans la Convention de Berne")
    juvenil_size = models.CharField(max_length=32, verbose_name="Taille des juvéniles", help_text="Exemple: 80 - 90 cm")
    adult_size = models.CharField(max_length=32, verbose_name="Taille des adultes", help_text="Exemple: 80 - 90 cm")
    life_expectancy = models.CharField(max_length=100, verbose_name="Espérance de vie", help_text="Exemple: 15 - 20 ans", default=15)
    main_mores = models.CharField(max_length=1, verbose_name="Moeurs principale", choices=MORES_CHOICES)
    activity_period = models.CharField(max_length=1, verbose_name="Période d'activité principale", choices=ACTIVITY_PERIOD_CHOICES)
    reproduction = models.CharField(max_length=1, verbose_name="Mode de reproduction", default="0", blank=True, choices=REPRODUCTIONS)
    reproduction_period = models.ManyToManyField(ReproductionPeriod, blank=True)
    preys = models.ManyToManyField(Prey, verbose_name="Proies")
    main_behavior = models.CharField(max_length=1, verbose_name="Tempérament", choices=BEHAVIOR_CHOICES)
    distribution = models.CharField(max_length=1024)
    biotops = models.ManyToManyField(Biotop, verbose_name="Biotopes")
    vivarium_size = models.CharField(max_length=128, verbose_name="Taille du terrarium", help_text="Exemple: Lxlxh - bassin: Lxlxl. Dimension en cm. Possibilité de mettre multiplicateur de l'animal selon l'OPAN: 1x0.55x0.5")
    slug = models.SlugField(unique=True)
    more_informations = models.TextField(verbose_name="Informations complémentaires", help_text="Informations complémentaires importantes")
    bite_dangerosity = models.CharField(max_length=1, verbose_name="Dangerosité de la morsure",
                                        choices=BITE_DANGEROSITY_CHOICES)
    difficulty_care = models.CharField(max_length=1, verbose_name="Difficulté de maintien",
                                       choices=DIFFICULTY_LEVEL_CHOICE)
    day_temperature = models.CharField(max_length=64, verbose_name="Température de jour", help_text="format : 18°C - 22°C")
    night_temperature = models.CharField(max_length=64, verbose_name="Température de nuit",
                                       help_text="format : 18°C - 22°C")
    humidity = models.CharField(max_length=64, verbose_name="humidité", help_text="format: 50% - 80%")
    life_community = models.ManyToManyField(LifeCommunity, verbose_name='Peut vivre en communauté')
    last_update = models.DateField(auto_now=True)
    last_owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True
        verbose_name = "Fiche d'élevage"
        verbose_name_plural = "Fiches d'élevage"

class Venom(models.Model):
    name = models.CharField(max_length=64)
    effects = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Venin"
        verbose_name_plural = "Venins"

class VenomousCard(Card):
    TOXICITY_LEVEL_CHOICES = (
        ('N', 'Non venimeux'),
        ('F', 'Faible toxicité'),
        ('A', 'Nécessite une surveillance active'),
        ('H', 'Hospitalisation immédiate recommandée'),
        ('I', 'Hospitalisation immédiate (risque de décès)')
    )
    toxicity_level = models.CharField(max_length=1, blank=True, verbose_name="Niveau de toxicité",
                                      choices=TOXICITY_LEVEL_CHOICES)
    venoms = models.ManyToManyField(Venom, verbose_name="Venins")

    class Meta:
        abstract = True

def snake_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "medias/uploads/snake/{0}/{1}/{2}".format(instance.genus, instance.species, filename)

class Snake(VenomousCard):
    DENTITIONS = (
        ('A', 'Aglyphe'),
        ('O', 'Opistoglyphe'),
        ('T', 'Opisthodonte'),
        ('P', 'Protégroglyphe'),
        ('S', 'Solénoglyphe')
    )
    dentition = models.CharField(max_length=1, verbose_name="Dentition", default='A', choices=DENTITIONS)
    image = ImageField(upload_to=snake_directory_path)

    class Meta:
        verbose_name = "Serpent"
        verbose_name_plural = "Serpents"

    def get_absolute_url(self):
        return reverse("snake_detail", kwargs={"slug": self.slug})

    def get_scientific_name(self):
        return f"{self.genus} {self.species}"

    def __str__(self):
        return self.get_scientific_name()

    def save(self, *args, **kwargs):
        self.genus = self.genus.capitalize()
        self.species = self.species.lower()
        if not self.slug:
            _slug = self.get_scientific_name()
            self.slug = slugify(_slug)
        return super().save(*args, **kwargs)

def arthropod_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "medias/uploads/arthropod/{0}/{1}/{2}".format(instance.genus, instance.species, filename)

class Arthropod(VenomousCard):
    image = ImageField(upload_to=arthropod_directory_path)

    class Meta:
        verbose_name = "Arthropode"
        verbose_name_plural = "Arthropodes"

    def get_absolute_url(self):
        return reverse("snake_detail", kwargs={"slug": self.slug})

    def get_scientific_name(self):
        return f"{self.genus} {self.species}"

    def __str__(self):
        return self.get_scientific_name()

    def save(self, *args, **kwargs):
        self.genus = self.genus.capitalize()
        self.species = self.species.lower()
        if not self.slug:
            _slug = self.get_scientific_name()
            self.slug = slugify(_slug)
        return super().save(*args, **kwargs)


def amphibian_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "medias/uploads/amphibian/{0}/{1}/{2}".format(instance.genus, instance.species, filename)


class Amphibian(Card):
    VOLUME_CALL_CHOICES = (
        ('A', 'Aphone'),
        ('D', 'Discret'),
        ('B', 'Bruyant')
    )
    image_egg = ImageField(upload_to=amphibian_directory_path, blank=True, verbose_name="Image d'une ponte")
    image_larve = ImageField(upload_to=amphibian_directory_path, blank=True, verbose_name="Image des larves")
    image = ImageField(upload_to=amphibian_directory_path, verbose_name="Image des adultes")
    volume_call = models.CharField(max_length=1, help_text="Volume sonnor du chant", choices=VOLUME_CALL_CHOICES)

    class Meta:
        verbose_name = "Amphibien"
        verbose_name_plural = "Amphibiens"

    def get_absolute_url(self):
        return reverse("amphibian_detail", kwargs={"slug": self.slug})

    def get_scientific_name(self):
        return f"{self.genus} {self.species}"

    def __str__(self):
        return self.get_scientific_name()

    def save(self, *args, **kwargs):
        self.genus = self.genus.capitalize()
        self.species = self.species.lower()
        if not self.slug:
            _slug = self.get_scientific_name()
            self.slug = slugify(_slug)
        return super().save(*args, **kwargs)


def lizard_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "medias/uploads/lizard/{0}/{1}/{2}".format(instance.genus, instance.species, filename)


class Lizard(Card):
    image = ImageField(upload_to=lizard_directory_path, verbose_name="Image des adultes")

    class Meta:
        verbose_name = "Lézard"
        verbose_name_plural = "Lézards"

    def get_absolute_url(self):
        return reverse("lizard_detail", kwargs={"slug": self.slug})

    def get_scientific_name(self):

card/forms.py
from django import forms
from django.forms import ModelForm
from .models import Card, Amphibian, Lizard
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Amphibian, Arthropod, Lizard, Snake, Turtle

class SnakeForm(ModelForm):
    class Meta:
        model = Snake
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

class ArthropodForm(ModelForm):
    class Meta:
        model = Arthropod
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

class AmphibianForm(ModelForm):
    class Meta:
        model = Amphibian
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

class LizardForm(ModelForm):
    class Meta:
        model = Lizard
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

class TurtleForm(ModelForm):
    class Meta:
        model = Turtle
        exclude = ['slug', 'last_owner', 'last_update']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Envoyer'))
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-3'
    helper.field_class = 'col-lg-9'

card/templates/unicorn/amphibian-detail.html
{% load thumbnail %}{% load static %}
<div class="row">
    <div class="col-md-4">
        {% thumbnail amphibian.image "400x300" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top"
                 alt="TerrarioPedia - Amphibiens - Fiche d'élevage {{ amphibian.get_scientific_name }}"/>
        {% endthumbnail %}
        {% thumbnail amphibian.image_egg "400x300" crop="center" as ime %}
            <img src="{{ ime.url }}" width="{{ ime.width }}" height="{{ ime.height }}" class="card-img-top mt-1"
                 alt="TerrarioPedia - Amphibiens - Fiche d'élevage {{ amphibian.get_scientific_name }}"/>
        {% endthumbnail %}
        {% thumbnail amphibian.image_larve "400x300" crop="center" as iml %}
            <img src="{{ iml.url }}" width="{{ iml.width }}" height="{{ iml.height }}" class="card-img-top mt-1"
                 alt="TerrarioPedia - Amphibiens - Fiche d'élevage {{ amphibian.get_scientific_name }}"/>
        {% endthumbnail %}
        <div class="row mt-1">
            <hr />
            <div class="col-sm-6">
                <b>Difficulté de détention</b><br />
                {% if amphibian.difficulty_care == 'N' %}
                <img src="{% static 'assets/images/jauges/1.png' %}" class="img-fluid" width="150" height="90" title="TerrarioPedia - Fiches d'élevage - Amphibiens - Difficulté de détention de {{ amphibian.get_scientific_name }}" />
                {% endif %}
                {% if amphibian.difficulty_care == 'B' %}
                <img src="{% static 'assets/images/jauges/2.png' %}" class="img-fluid" width="150" height="90" title="TerrarioPedia - Fiches d'élevage - Amphibiens - Difficulté de détention de {{ amphibian.get_scientific_name }}" />
                {% endif %}
                {% if amphibian.difficulty_care == 'E' %}
                <img src="{% static 'assets/images/jauges/3.png' %}" class="img-fluid" width="150" height="90" title="TerrarioPedia - Fiches d'élevage - Amphibiens - Difficulté de détention de {{ amphibian.get_scientific_name }}" />
                {% endif %}
                {% if amphibian.difficulty_care == 'X' %}
                <img src="{% static 'assets/images/jauges/4.png' %}" class="img-fluid" width="150" height="90" title="TerrarioPedia - Fiches d'élevage - Amphibiens - Difficulté de détention de {{ amphibian.get_scientific_name }}" />
                {% endif %}
            </div>
            <div class="col-sm-6">
                <strong>Danger de la morsure</strong><br />
                {% if amphibian.bite_dangerosity == 'I' %}
                <img src="{% static 'assets/images//jauges/1.png' %}" class="img-fluid" width="150" height="90" title="TerrarioPedia - Difficulté de détention de {{ object.get_scientific_name }}" />
                {% endif %}
                {% if amphibian.bite_dangerosity == 'P' %}
                <img src="{% static 'assets/images//jauges/2.png' %}" class="img-fluid" width="150" height="90" title="TerrarioPedia - Difficulté de détention de {{ object.get_scientific_name }}" />
                {% endif %}
                {% if amphibian.bite_dangerosity == 'D' %}
                <img src="{% static 'assets/images//jauges/3.png' %}" class="img-fluid" width="150" height="90" title="TerrarioPedia - Difficulté de détention de {{ object.get_scientific_name }}" />
                {% endif %}
                {% if amphibian.bite_dangerosity == 'E' %}
                <img src="{% static 'assets/images//jauges/4.png' %}" class="img-fluid" width="150" height="90" title="TerrarioPedia - Difficulté de détention de {{ object.get_scientific_name }}" />
                {% endif %}
            </div>
            <hr />
        </div>
        <p>
            {{ amphibian.more_informations }}
        </p>
        <hr />
        <a href="{% url 'card:amphibian-edit' amphibian.slug %}" class="btn btn-warning btn-block" title="TerrarioPedia - Amphibiens - Fiches d'élevage de {{ amphibian.get_scientific_name }} - Editer">Editer</a><br />
        <strong>Dernière modification</strong><br /> {{ amphibian.last_owner }} - {{ amphibian.last_update|date:"d F Y" }}
    </div>
    <div class="col-md-6">
        <h2>{{ amphibian.get_scientific_name }}</h2>
        <p>Espèce{% if not amphibian.is_cites %} non{% endif %} CITES
            {% if amphibian.bern_convention_annex %}- annexe {{ amphibian.bern_convention_annex }}{% endif %}</p>
        <strong>Description</strong>
        <div class="table-responsive">
            <table class="table search-table align-middle text-nowrap">
                <tbody>
                    <tr class="search item">
                        <td scope="row">Taille des juvéniles</td>
                        <td>{{ amphibian.juvenil_size }} cm</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Taille des adultes</td>
                        <td>{{ amphibian.adult_size }} cm</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <strong>Biologie</strong>
        <div class="table-responsive">
            <table class="table search-table align-middle text-nowrap">
                <tbody>
                    <tr class="search item">
                        <td scope="row">Espérance de vie</td>
                        <td>{{ amphibian.life_expectancy }} ans</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Moeurs principal</td>
                        <td>{{ amphibian.get_main_mores_display }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Tempérament</td>
                        <td>{{ amphibian.get_main_behavior_display }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Période d'activité</td>
                        <td>{{ amphibian.get_activity_period_display }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Volume du chant</td>
                        <td>{{ amphibian.get_volume_call_display }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Reproduction</td>
                        <td>{{ amphibian.get_reproduction_display }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Période de reproduction</td>
                        <td>
                            {% for reproduction_period in amphibian.reproduction_period.all %}
                                {{ reproduction_period }}{% if not forloop.last %}<br /> {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Proies</td>
                        <td>
                            {% for prey in amphibian.preys.all %}
                                {{ prey }}{% if not forloop.last %}<br /> {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <strong>Environnements</strong>
        <div class="table-responsive">
            <table class="table search-table align-middle text-nowrap">
                <tbody>
                    <tr class="search item">
                        <td scope="row">Distribution</td>
                        <td>{{ amphibian.distribution }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Biotopes</td>
                        <td>
                            {% for biotop in amphibian.biotops.all %}
                            {{ biotop }}{% if not forloop.last %}<br /> {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <strong>En captivité</strong>
        <div class="table-responsive">
            <table class="table table-responsive search-table align-middle text-nowrap">
                <tbody>
                    <tr class="search item">
                        <td scope="row">Difficulté de détention</td>
                        <td>{{ amphibian.get_difficulty_care_display }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Dimension du Terrarium</td>
                        <td>{{ amphibian.vivarium_size }} cm</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Température jour / nuit</td>
                        <td>{{ amphibian.day_temperature }} / {{ amphibian.night_temperature }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Humidité</td>
                        <td>{{ amphibian.humidity }}</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Dimension du Terrarium</td>
                        <td>{{ amphibian.vivarium_size }} cm</td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Vie en communauté</td>
                        <td>
                            {% for life_community in amphibian.life_community.all %}
                            {{ life_community }}{% if not forloop.last %}<br /> {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr class="search item">
                        <td scope="row">Dangerosité de la morsure</td>
                        <td>{{ amphibian.get_bite_dangerosity_display }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

card/templates/unicorn/amphibian-list.html
{% load sorl_thumbnail %}
<div class="row">
    {% for amphibian in amphibians %}
        <div class="col-sm-6 col-xl-3">
            <div class="card overflow-hidden rounded-2">
                <div class="position-relative">
                    <a href="{% url 'card:amphibian-detail' amphibian.slug %}"
                       title="TerrarioPedia - Amphibiens - Fiche d'élevage {{ amphibian.get_scientific_name }}">
                       {% thumbnail amphibian.image "335x235" crop="center" as im %}
                         <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top"
                         alt="TerrarioPedia - Amphibiens - Fiche d'élevage {{ amphibian.get_scientific_name }}"/>
                        {% endthumbnail %}</a>
                </div>
                <div class="card-body pt-3 p-4">
                    <h6 class="fw-semibold fs-4">{{ amphibian.get_scientific_name }}</h6>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

card/templates/unicorn/arthropod-list.html
{% load sorl_thumbnail %}
<div class="row">
    {% for arthropod in arthropods %}
    <div class="col-sm-6 col-xl-3">
        <div class="card overflow-hidden rounded-2">
            <div class="position-relative">
                <a href="{% url 'card:arthropod-detail' arthropod.slug %}"
                       title="TerrarioPedia - Arthropodes - Fiche d'élevage {{ arthropod.get_scientific_name }}">
                    {% thumbnail arthropod.image "335x235" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top"
                         alt="TerrarioPedia - Serpents - Fiche d'élevage {{ arthropod.get_scientific_name }}"/>
                    {% endthumbnail %}</a>
            </div>
            <div class="card-body pt-3 p-4">
                <h6 class="fw-semibold fs-4">{{ arthropod.get_scientific_name }}</h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

card/templates/unicorn/snake-list.html
{% load sorl_thumbnail %}
<div class="row">
    {% for snake in snakes %}
    <div class="col-sm-6 col-xl-3">
        <div class="card overflow-hidden rounded-2">
            <div class="position-relative">
                <a href="{% url 'card:snake-detail' snake.slug %}"
                       title="TerrarioPedia - Serpents - Fiche d'élevage {{ snake.get_scientific_name }}">
                    {% thumbnail snake.image "335x235" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="card-img-top"
                         alt="TerrarioPedia - Serpents - Fiche d'élevage {{ snake.get_scientific_name }}" />
                    {% endthumbnail %}</a>
            </div>
            <div class="card-body pt-3 p-4">
                <h6 class="fw-semibold fs-4">{{ snake.get_scientific_name }}</h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>