ads/urls.py
from django.urls import path
from .views import AdsList, AdsDetail, AdsCreateView, AdsUpdateView, AdsDeleteView, AdsOwnList

app_name = "ads"
urlpatterns = [
    path("", AdsList, name="ads-list"),
    path("ajouter", AdsCreateView.as_view(), name="ads-new"),
    path("mes-annonces", AdsOwnList, name="ads-own-list"),
    path("<int:pk>", AdsDetail, name="ads-detail"),
    path("<int:pk>/editer", AdsUpdateView.as_view(), name="ads-edit"),
    path("<int:pk>/supprimer", AdsDeleteView.as_view(), name="ads-delete"),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import register, view_login, view_logout

from .views import index

urlpatterns = [
    path('', index, name="home"),
    path('admin/', admin.site.urls),
    path('unicorn/', include("django_unicorn.urls")),
    path('fiches-d-elevage/', include('card.urls', namespace="card")),
    path('petites-annonces/', include('ads.urls', namespace="ads")),
    path("terrariopedia/", include("django.contrib.flatpages.urls")),
    path("communaute/", include('member.urls', namespace="member")),
    path("documentations/", include('documentation.urls', namespace="documentation")),
    path("register", register, name="register"),
    path("login", view_login, name="login"),
    path("logout", view_logout, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

card/urls.py
from django.urls import path

from .views import AmphibianList, AmphibianDetail, AmphibianCreateView, AmphibianUpdateView, \
    ArthropodList, ArthropodDetail, ArthropodCreateView, ArthropodUpdateView, \
    LizardList, LizardDetail, LizardCreateView, LizardUpdateView, \
    SnakeList, SnakeDetail, SnakeCreateView, SnakeUpdateView, \
    TurtleList, TurtleDetail, TurtleCreateView, TurtleUpdateView

app_name = "card"
urlpatterns = [
    path("amphibiens/", AmphibianList, name="amphibian-list"),
    path("amphibiens/ajouter", AmphibianCreateView.as_view(), name="amphibian-new"),
    path("amphibiens/<slug:slug>/editer", AmphibianUpdateView.as_view(), name="amphibian-edit"),
    path("amphibiens/<slug:slug>", AmphibianDetail, name="amphibian-detail"),

    path("arthropodes/", ArthropodList, name="arthropod-list"),
    path("arthropodes/ajouter", ArthropodCreateView.as_view(), name="arthropod-new"),
    path("arthropodes/<slug:slug>/editer", ArthropodUpdateView.as_view(), name="arthropod-edit"),
    path("arthropodes/<slug:slug>", ArthropodDetail, name="arthropod-detail"),

    path("lezards/", LizardList, name="lizard-list"),
    path("lezards/ajouter", LizardCreateView.as_view(), name="lizard-new"),
    path("lezards/<slug:slug>/editer", LizardUpdateView.as_view(), name="lizard-edit"),
    path("lezards/<slug:slug>", LizardDetail, name="lizard-detail"),

    path("serpents/", SnakeList, name="snake-list"),
    path("serpents/ajouter", SnakeCreateView.as_view(), name="snake-new"),
    path("serpents/<slug:slug>/editer", SnakeUpdateView.as_view(), name="snake-edit"),
    path("serpents/<slug:slug>", SnakeDetail, name="snake-detail"),

    path("tortues/", TurtleList, name="turtle-list"),
    path("tortues/ajouter", TurtleCreateView.as_view(), name="turtle-new"),
    path("tortues/<slug:slug>/editer", TurtleUpdateView.as_view(), name="turtle-edit"),
    path("tortues/<slug:slug>", TurtleDetail, name="turtle-detail"),
]

documentation/urls.py
from django.urls import path
from .views import DocumentationList, DocumentationDetail, DocumentationCreateView, DocumentationUpdateView

app_name = "documentation"
urlpatterns = [
    path("ajouter/", DocumentationCreateView.as_view(), name="documentation-new"),
    path("<str:category>/", DocumentationList, name="documentation-list"),
    path("<str:category>/<slug:slug>", DocumentationDetail, name="documentation-detail"),
    path("<str:category>/<slug:slug>/editer", DocumentationUpdateView.as_view(), name="documentation-edit")
]

member/urls.py
from django.urls import path
from .views import CommunityList, ChangePasswordView, CommunityDetail, MemberUpdateView

app_name = "member"
urlpatterns = [
    path('membres/', CommunityList, name="member-list"),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('membres/<int:pk>/editer', MemberUpdateView.as_view(), name="member-edit"),
    path('membres/<int:pk>', CommunityDetail, name="member-detail"),
]

templates/base.html
<!-- index.html -->
{% load unicorn %}{% load static %}{% load thumbnail %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TerrarioPedia - {% block page_title %}{% endblock %}</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'assets/images/logos/favicon.png' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />
  {% unicorn_scripts %}
</head>

<body>
{% csrf_token %}
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="{% url 'home' %}" class="text-nowrap logo-img">
            <strong>TerrarioPedia</strong>
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">TerrarioPedia</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="/terrariopedia/philosophie" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/light-bulb.png' %}" width="24" height="24" alt="TerrarioPedia - Fiches d'élevage Amphibiens" />
                </span>
                <span class="hide-menu">Philosophie</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="/terrariopedia/guidelines" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/guidelines.png' %}" width="24" height="24" alt="TerrarioPedia - Fiches d'élevage Amphibiens" />
                </span>
                <span class="hide-menu">Guidelines</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'member:member-list' %}" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/community.png' %}" width="24" height="24" alt="TerrarioPedia - Communauté" />
                </span>
                <span class="hide-menu">Communauté</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Fiches d'élevage</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'card:amphibian-list' %}" title="TerrarioPedia - Fiches d'élevage Amphibiens" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/frog.png' %}" width="24" height="24" alt="TerrarioPedia - Fiches d'élevage Amphibiens" />
                </span>
                <span class="hide-menu">Amphibiens</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'card:arthropod-list' %}" title="TerrarioPedia - Fiches d'élevage Arthropodes" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/spider.png' %}" width="24" height="24" alt="TerrarioPedia - Fiches d'élevage Amphibiens" />
                </span>
                <span class="hide-menu">Arthropodes</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'card:lizard-list' %}" title="TerrarioPedia - Fiches d'élevage Lézards" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/lizard.png' %}" width="24" height="24" alt="TerrarioPedia - Fiches d'élevage Amphibiens" />
                </span>
                <span class="hide-menu">Lézards</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'card:snake-list' %}" title="TerrarioPedia - Fiches d'élevage Serpents" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/snake.png' %}" width="24" height="24" alt="TerrarioPedia - Fiches d'élevage Amphibiens" />
                </span>
                <span class="hide-menu">Serpents</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'card:turtle-list' %}" title="TerrarioPedia - Fiches d'élevage Tortues" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/turtle.png' %}" width="24" height="24" alt="TerrarioPedia - Fiches d'élevage Tortues" />
                </span>
                <span class="hide-menu">Tortues</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Petites annonces</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'ads:ads-list' %}" title="TerrarioPedia - Petites annonces" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/cart.png' %}" width="24" height="24" alt="TerrarioPedia - Petites annonces" />
                </span>
                <span class="hide-menu">Voir les annonces</span>
              </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'ads:ads-own-list' %}" title="TerrarioPedia - Mes annonces" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/list.png' %}" width="24" height="24" alt="TerrarioPedia - Fiches d'élevage Amphibiens" />
                </span>
                <span class="hide-menu">Mes annonces</span>
              </a>
            </li>
            {% endif %}
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Documentations</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'documentation:documentation-list' 'amphibiens' %}" title="TerrarioPedia - Documentation Amphibiens" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/knowledge.png' %}" width="24" height="24" alt="TerrarioPedia - Documentations Amphibiens" />
                </span>
                <span class="hide-menu">Amphibiens</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'documentation:documentation-list' 'arthropodes' %}" title="TerrarioPedia - Documentation Arthropodes" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/knowledge.png' %}" width="24" height="24" alt="TerrarioPedia - Documentations Amphibiens" />
                </span>
                <span class="hide-menu">Arthropodes</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'documentation:documentation-list' 'lezards' %}" title="TerrarioPedia - Documentations Lézards" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/knowledge.png' %}" width="24" height="24" alt="TerrarioPedia - Documentations Amphibiens" />
                </span>
                <span class="hide-menu">Lézards</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'documentation:documentation-list' 'serpents' %}" title="TerrarioPedia - Documentations Serpents" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/knowledge.png' %}" width="24" height="24" alt="TerrarioPedia - Documentations Amphibiens" />
                </span>
                <span class="hide-menu">Serpents</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'documentation:documentation-list' 'tortues' %}" title="TerrarioPedia - Documentations Tortues" aria-expanded="false">
                <span>
                  <img src="{% static 'assets/images/icons/knowledge.png' %}" width="24" height="24" alt="TerrarioPedia -Documentations Tortues" />
                </span>
                <span class="hide-menu">Tortues</span>
              </a>
            </li>
          </ul>
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header Start -->
      <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
              <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                <i class="ti ti-menu-2"></i>
              </a>
            </li>

          </ul>
          <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
              <a href="{% url 'ads:ads-new' %}" title="TerrarioPedia - Publier une annonce" class="btn btn-primary">Publier une annonce</a>
              {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  {% thumbnail request.user.profile.profile_picture "35x35" crop="center" as im %}
                    <img src="{{ im.url }}" class="rounded-circle" width="{{ im.width }}" height="{{ im.height }}" alt="TerrarioPedia - {{ request.user.get_full_name }}" />
                  {% empty %}
                  <img src="{% static 'assets/images/profile/user-1.jpg' %}" class="rounded-circle" width="35" height="35" alt="TerrarioPedia - {{ request.user.get_full_name }}" />
                  {% endthumbnail %}
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                  <div class="message-body">
                    <a href="{% url 'member:member-detail' request.user.pk %}" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-user fs-6"></i>
                      <p class="mb-0 fs-3">Mon profile</p>
                    </a>
                    <hr />
                    <a href="{% url 'logout' %}" class="btn btn-outline-primary mx-3 mt-2 d-block">Se déconnecter</a>
                  </div>
                </div>
              </li>
              {% else %}
              <a href="{% url 'login' %}" title="TerrarioPedia - Connexion" class="btn btn-primary ms-3">Connexion</a>
              <a href="{% url 'register' %}" title="TerrarioPedia - Inscription" class="btn btn-outline-primary ms-3">S'inscrire</a>
              {% endif %}
            </ul>
          </div>
        </nav>
      </header>
      <!--  Header End -->
      <div class="container-fluid mw-100">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  <script src="{% static 'assets/libs/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/sidebarmenu.js' %}"></script>
  <script src="{% static 'assets/js/app.min.js' %}"></script>
  <script src="{% static 'assets/libs/simplebar/dist/simplebar.js' %}"></script>
</body>

</html>